# Basic
title: gal资源部
subtitle: GalResourcesClub
welcome_message: <a href="https://github.com/GalResourcesClub/GalResourcesClub.GitHub.io" target="_blank">Download the theme</a>
description: 欢迎来到gal资源部~.
creator: <a href="http://onev.cat">@onevcat</a>

url: "GalResourcesClub.GitHub.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: #FFB6C1

# The blog button should not be removed.
blog_button:
    title: GalRC
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: #
    # duoshuo: 
    
# Social
social:
    weibo: ##
    github: GalResourcesClub
    twitter: ##
    gplus: ##
    mail: ##

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
    
# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 435a5d2d8f65641351b0                            #生成的clientID
  clientSecret: bea1fc274d29b5e812c2a99556cc8076da43ba87    #生成的clientSecret
  repo: GalResourcesClub.github.io    #仓库名称
  owner: GalResourcesClub    #github用户名
  admin: GalResourcesClub
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

